# Generated by Django 4.1.2 on 2022-10-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendCard', models.CharField(max_length=500)),
                ('toCard', models.CharField(max_length=500)),
                ('messageTime', models.CharField(max_length=500)),
                ('message', models.CharField(max_length=1000)),
                ('isRead', models.BooleanField(default=False)),
            ],
        ),
    ]
