# Generated by Django 4.1.2 on 2022-10-30 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('card', models.CharField(max_length=200, unique=True)),
                ('school', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=500)),
                ('role', models.CharField(max_length=500)),
                ('createdAt', models.CharField(max_length=500)),
                ('isManager', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['card'],
            },
        ),
        migrations.CreateModel(
            name='RelaNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=500)),
                ('userInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemData.userinfo', to_field='card')),
            ],
            options={
                'unique_together': {('userInfo', 'number')},
            },
        ),
    ]
