# Generated by Django 4.1.2 on 2022-11-08 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemData', '0001_initial'),
        ('ProcessFile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processfile',
            options={'ordering': ['-createdAt']},
        ),
        migrations.AlterUniqueTogether(
            name='processfile',
            unique_together={('userInfo', 'fileName')},
        ),
        migrations.RemoveField(
            model_name='processfile',
            name='fileType',
        ),
    ]
