# Generated by Django 4.1.2 on 2022-10-30 00:18

import ExperiData.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('systemData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperiData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataType', models.CharField(max_length=500)),
                ('testTime', models.CharField(max_length=500)),
                ('createdAt', models.CharField(max_length=500)),
                ('processId', models.CharField(max_length=500)),
                ('sampleId', models.CharField(max_length=500)),
                ('dataName', models.CharField(max_length=500)),
                ('data', models.FileField(upload_to=ExperiData.models.ExperiDataPath)),
                ('rank', models.CharField(max_length=500)),
                ('isPublic', models.BooleanField(default=False)),
                ('isShow', models.BooleanField(default=True)),
                ('userInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemData.userinfo', to_field='card')),
            ],
            options={
                'ordering': ['dataType', '-createdAt'],
                'unique_together': {('userInfo', 'dataType', 'dataName')},
            },
        ),
    ]
