# Generated by Django 4.1.2 on 2022-10-30 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('systemData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatype', models.CharField(max_length=500)),
                ('fileName', models.CharField(max_length=500)),
                ('createdAt', models.CharField(max_length=500)),
                ('describe', models.CharField(max_length=500)),
                ('userInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemData.userinfo', to_field='card')),
            ],
            options={
                'ordering': ['datatype', '-createdAt'],
            },
        ),
    ]
